[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--emit=files"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
# args = ["clippy", "-D", "warnings"]
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]


[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.ci-flow]
dependencies = [
    "build",
    "test"
]

[tasks.ci-flow-windows]
dependencies = [
    "build",
    "test"
]

